### ISSUE TITLE
[Breadcrumb] Cannot edit breadcrumb in template editor

### ISSUE THREAD

**Issue by cjelger** [adobe/aem-core-wcm-components#1146]
## Bug Report

**Current Behavior**
When it's added to a page template, the breadcrumb component cannot be edited in the template editor and actually "breaks" the rendering of the template in the Editor because it throws a NPE.

**Expected behavior/code**
The component should be editable in the template editor.

**Environment**
Latest AEM Cloud SDK.

**Possible Solution**
A brute-force solution is to simply ignore all pages in the template editor and add
```
if (!currentPage.getPath().startsWith("/content")) {
    return Collections.emptyList();
}
```
at the start of the `getItems()` method.

**Comment by jckautzmann** [comment]
I was able to reproduce it and observed following error:
```
Caused by: java.lang.NullPointerException: null
    at com.adobe.cq.wcm.core.components.internal.models.v1.AbstractListItemImpl.<init>(AbstractListItemImpl.java:40) [com.adobe.cq.core.wcm.components.core:2.11.1.SNAPSHOT]
    at com.adobe.cq.wcm.core.components.internal.models.v1.PageListItemImpl.<init>(PageListItemImpl.java:53) [com.adobe.cq.core.wcm.components.core:2.11.1.SNAPSHOT]
    at com.adobe.cq.wcm.core.components.internal.models.v1.NavigationItemImpl.<init>(NavigationItemImpl.java:38) [com.adobe.cq.core.wcm.components.core:2.11.1.SNAPSHOT]
    at com.adobe.cq.wcm.core.components.internal.models.v1.BreadcrumbItemImpl.<init>(BreadcrumbItemImpl.java:33) [com.adobe.cq.core.wcm.components.core:2.11.1.SNAPSHOT]
    at com.adobe.cq.wcm.core.components.internal.models.v1.BreadcrumbImpl.createItems(BreadcrumbImpl.java:105) [com.adobe.cq.core.wcm.components.core:2.11.1.SNAPSHOT]
    at com.adobe.cq.wcm.core.components.internal.models.v1.BreadcrumbImpl.getItems(BreadcrumbImpl.java:83) [com.adobe.cq.core.wcm.components.core:2.11.1.SNAPSHOT]
```

**Comment by jckautzmann** [comment]
I created a fix:
https://github.com/adobe/aem-core-wcm-components/pull/1147

**Comment by jckautzmann** [comment]
The NPE is thrown when one of the page (breadcrumb item) does not have a `jcr:content` node.
