### ISSUE TITLE
[Image] broken images in the component library

### ISSUE THREAD

**Issue by jckautzmann** [adobe/aem-core-wcm-components#1353]
## Bug Report

**Current Behavior**
All images are broken on the component library pages, e.g.:
http://localhost:4502/content/core-components-examples/library/page-authoring/image.html

**Environment**
- AEMaaCS
- Core Components: 2.13.3-SNAPSHOT (installed with `mvn clean install -PautoInstallSinglePackage -Pcloud`)
- JRE version: 11

**Additional context / Screenshots**
![Screenshot 2021-01-19 at 13 55 02](https://user-images.githubusercontent.com/6152300/105060409-a6720e00-5a78-11eb-8953-14dbde7c38c5.png)

**Comment by jckautzmann** [comment]
The issue does not happen with newly added images in DAM, nor with the SVG icons. 
It happens with the images from the component library below `/content/dam/core-components-examples/library/sample-assets`, e.g. `lava-into-ocean.jpg`.
So it probably happens when importing those images into DAM when the package is installed.

**Comment by jckautzmann** [comment]
Many workflow errors in the logs. e.g.:
```
25.01.2021 16:41:20.441 *WARN* [JobHandler: /var/workflow/instances/server0/2021-01-25/asset_processing_on_sdk_8:/content/dam/core-components-examples/library/sample-assets/snowy-mountain-glacier.jpg/jcr:content/renditions/original] com.day.cq.dam.commons.handler.StandardImageHandler getImage: error while reading image at path [/content/dam/core-components-examples/library/sample-assets/snowy-mountain-glacier.jpg/jcr:content/renditions/original]:
org.apache.commons.imaging.ImageReadException: Can't parse this format.
	at org.apache.commons.imaging.Imaging.getImageParser(Imaging.java:761) [org.apache.commons.commons-imaging:1.0.0.R1725432-B002]
	at org.apache.commons.imaging.Imaging.getBufferedImage(Imaging.java:1402) [org.apache.commons.commons-imaging:1.0.0.R1725432-B002]
	at org.apache.commons.imaging.Imaging.getBufferedImage(Imaging.java:1370) [org.apache.commons.commons-imaging:1.0.0.R1725432-B002]
	at com.day.cq.dam.commons.handler.StandardImageHandler.getImage(StandardImageHandler.java:245) [com.day.cq.dam.cq-dam-commons:5.13.142]
	at com.day.cq.dam.core.impl.handler.JpegHandler.getImage(JpegHandler.java:88) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.cache.CQBufferedImageCache.getImage(CQBufferedImageCache.java:123) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.createImageLayer(CommonsGfxRenderer.java:502) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.createLayer(CommonsGfxRenderer.java:165) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.render(CommonsGfxRenderer.java:116) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.adobe.cq.gfx.impl.GfxImpl.render(GfxImpl.java:109) [com.adobe.cq.cq-gfx:1.6.4]
	at com.day.cq.dam.core.impl.RenditionMakerImpl$PlanBasedTemplate.apply(RenditionMakerImpl.java:139) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.RenditionMakerImpl.generateRenditions(RenditionMakerImpl.java:218) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.process.CreateWebEnabledImageProcess.createWebEnabledImage(CreateWebEnabledImageProcess.java:163) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.process.ThumbnailProcess.execute(ThumbnailProcess.java:132) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.workflow.compatibility.CQWorkflowProcessRunner.execute(CQWorkflowProcessRunner.java:93) [com.day.cq.workflow.cq-workflow-impl:6.3.12]
	at com.adobe.granite.workflow.core.job.HandlerBase.executeProcess(HandlerBase.java:191) [com.adobe.granite.workflow.core:2.1.40]
	at com.adobe.granite.workflow.core.job.JobHandler.process(JobHandler.java:271) [com.adobe.granite.workflow.core:2.1.40]
	at org.apache.sling.event.impl.jobs.JobConsumerManager$JobConsumerWrapper.process(JobConsumerManager.java:502) [org.apache.sling.event:4.2.12]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.startJob(JobQueueImpl.java:293) [org.apache.sling.event:4.2.12]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.access$100(JobQueueImpl.java:60) [org.apache.sling.event:4.2.12]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl$1.run(JobQueueImpl.java:229) [org.apache.sling.event:4.2.12]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
25.01.2021 16:41:20.441 *WARN* [JobHandler: /var/workflow/instances/server0/2021-01-25/asset_processing_on_sdk_19:/content/dam/core-components-examples/library/sample-assets/lava-into-ocean.jpg/jcr:content/renditions/original] com.day.cq.dam.commons.handler.StandardImageHandler getImage: error while reading image at path [/content/dam/core-components-examples/library/sample-assets/lava-into-ocean.jpg/jcr:content/renditions/original]:
org.apache.commons.imaging.ImageReadException: Can't parse this format.
	at org.apache.commons.imaging.Imaging.getImageParser(Imaging.java:761) [org.apache.commons.commons-imaging:1.0.0.R1725432-B002]
	at org.apache.commons.imaging.Imaging.getBufferedImage(Imaging.java:1402) [org.apache.commons.commons-imaging:1.0.0.R1725432-B002]
	at org.apache.commons.imaging.Imaging.getBufferedImage(Imaging.java:1370) [org.apache.commons.commons-imaging:1.0.0.R1725432-B002]
	at com.day.cq.dam.commons.handler.StandardImageHandler.getImage(StandardImageHandler.java:245) [com.day.cq.dam.cq-dam-commons:5.13.142]
	at com.day.cq.dam.core.impl.handler.JpegHandler.getImage(JpegHandler.java:88) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.cache.CQBufferedImageCache.getImage(CQBufferedImageCache.java:123) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.createImageLayer(CommonsGfxRenderer.java:502) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.createLayer(CommonsGfxRenderer.java:165) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.render(CommonsGfxRenderer.java:116) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.adobe.cq.gfx.impl.GfxImpl.render(GfxImpl.java:109) [com.adobe.cq.cq-gfx:1.6.4]
	at com.day.cq.dam.core.impl.RenditionMakerImpl$PlanBasedTemplate.apply(RenditionMakerImpl.java:139) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.RenditionMakerImpl.generateRenditions(RenditionMakerImpl.java:218) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.process.CreateWebEnabledImageProcess.createWebEnabledImage(CreateWebEnabledImageProcess.java:163) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.process.ThumbnailProcess.execute(ThumbnailProcess.java:132) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.workflow.compatibility.CQWorkflowProcessRunner.execute(CQWorkflowProcessRunner.java:93) [com.day.cq.workflow.cq-workflow-impl:6.3.12]
	at com.adobe.granite.workflow.core.job.HandlerBase.executeProcess(HandlerBase.java:191) [com.adobe.granite.workflow.core:2.1.40]
	at com.adobe.granite.workflow.core.job.JobHandler.process(JobHandler.java:271) [com.adobe.granite.workflow.core:2.1.40]
	at org.apache.sling.event.impl.jobs.JobConsumerManager$JobConsumerWrapper.process(JobConsumerManager.java:502) [org.apache.sling.event:4.2.12]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.startJob(JobQueueImpl.java:293) [org.apache.sling.event:4.2.12]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.access$100(JobQueueImpl.java:60) [org.apache.sling.event:4.2.12]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl$1.run(JobQueueImpl.java:229) [org.apache.sling.event:4.2.12]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
25.01.2021 16:41:20.441 *WARN* [JobHandler: /var/workflow/instances/server0/2021-01-25/asset_processing_on_sdk_15:/content/dam/core-components-examples/library/sample-assets/lava-rock-formation.jpg/jcr:content/renditions/original] com.day.cq.dam.commons.handler.StandardImageHandler getImage: error while reading image at path [/content/dam/core-components-examples/library/sample-assets/lava-rock-formation.jpg/jcr:content/renditions/original]:
org.apache.commons.imaging.ImageReadException: Can't parse this format.
	at org.apache.commons.imaging.Imaging.getImageParser(Imaging.java:761) [org.apache.commons.commons-imaging:1.0.0.R1725432-B002]
	at org.apache.commons.imaging.Imaging.getBufferedImage(Imaging.java:1402) [org.apache.commons.commons-imaging:1.0.0.R1725432-B002]
	at org.apache.commons.imaging.Imaging.getBufferedImage(Imaging.java:1370) [org.apache.commons.commons-imaging:1.0.0.R1725432-B002]
	at com.day.cq.dam.commons.handler.StandardImageHandler.getImage(StandardImageHandler.java:245) [com.day.cq.dam.cq-dam-commons:5.13.142]
	at com.day.cq.dam.core.impl.handler.JpegHandler.getImage(JpegHandler.java:88) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.cache.CQBufferedImageCache.getImage(CQBufferedImageCache.java:123) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.createImageLayer(CommonsGfxRenderer.java:502) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.createLayer(CommonsGfxRenderer.java:165) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.gfx.CommonsGfxRenderer.render(CommonsGfxRenderer.java:116) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.adobe.cq.gfx.impl.GfxImpl.render(GfxImpl.java:109) [com.adobe.cq.cq-gfx:1.6.4]
	at com.day.cq.dam.core.impl.RenditionMakerImpl$PlanBasedTemplate.apply(RenditionMakerImpl.java:139) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.RenditionMakerImpl.generateRenditions(RenditionMakerImpl.java:218) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.process.CreateWebEnabledImageProcess.createWebEnabledImage(CreateWebEnabledImageProcess.java:163) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.process.ThumbnailProcess.execute(ThumbnailProcess.java:132) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.workflow.compatibility.CQWorkflowProcessRunner.execute(CQWorkflowProcessRunner.java:93) [com.day.cq.workflow.cq-workflow-impl:6.3.12]
	at com.adobe.granite.workflow.core.job.HandlerBase.executeProcess(HandlerBase.java:191) [com.adobe.granite.workflow.core:2.1.40]
	at com.adobe.granite.workflow.core.job.JobHandler.process(JobHandler.java:271) [com.adobe.granite.workflow.core:2.1.40]
	at org.apache.sling.event.impl.jobs.JobConsumerManager$JobConsumerWrapper.process(JobConsumerManager.java:502) [org.apache.sling.event:4.2.12]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.startJob(JobQueueImpl.java:293) [org.apache.sling.event:4.2.12]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl.access$100(JobQueueImpl.java:60) [org.apache.sling.event:4.2.12]
	at org.apache.sling.event.impl.jobs.queues.JobQueueImpl$1.run(JobQueueImpl.java:229) [org.apache.sling.event:4.2.12]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by jckautzmann** [comment]
Other errors in the logs, such as:
```
25.01.2021 16:41:20.470 *ERROR* [Thread-176] com.day.cq.dam.core.impl.ui.preview.FolderPreviewUpdaterImpl error while executing folder thumbnail update job: /content/dam/core-components-examples/library/sample-assets/snowy-mountain-glacier.jpg
java.lang.IllegalArgumentException: width or height <= 0
	at com.day.image.Layer.init(Layer.java:3181) [day-commons-gfx:2.1.50]
	at com.day.image.Layer.<init>(Layer.java:501) [day-commons-gfx:2.1.50]
	at com.day.cq.dam.core.impl.ui.preview.FolderPreviewGenerator$FolderPreviewCreator.createPreview(FolderPreviewGenerator.java:292) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.ui.preview.AssetDrivenFolderPreviewGenerator.generate(AssetDrivenFolderPreviewGenerator.java:245) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.ui.preview.FolderPreviewUpdaterImpl.updateFolderThumbnail(FolderPreviewUpdaterImpl.java:151) [com.day.cq.dam.cq-dam-core:5.13.250]
	at com.day.cq.dam.core.impl.ui.preview.FolderPreviewUpdaterImpl.run(FolderPreviewUpdaterImpl.java:208) [com.day.cq.dam.cq-dam-core:5.13.250]
	at java.base/java.lang.Thread.run(Thread.java:834)
25.01.2021 16:41:20.475 *ERROR* [Thread-176] com.day.cq.commons.ImageHelper Error while creating layer.
25.01.2021 16:41:20.476 *ERROR* [Thread-176] com.day.cq.dam.core.impl.ui.preview.AbstractPreviewCreator Cannot get layer with the proxy rendition stream
25.01.2021 16:41:20.477 *ERROR* [Thread-176] com.day.cq.commons.ImageHelper Error while creating layer.
25.01.2021 16:41:20.477 *WARN* [Thread-176] com.day.cq.dam.core.impl.ui.preview.AbstractPreviewCreator Unable to create layer for /content/dam/core-components-examples/library/sample-assets/snowy-mountain-glacier.jpg
25.01.2021 16:41:20.478 *ERROR* [Thread-176] com.day.cq.commons.ImageHelper Error while creating layer.
25.01.2021 16:41:20.479 *ERROR* [Thread-176] com.day.cq.dam.core.impl.ui.preview.AbstractPreviewCreator Cannot get layer with the proxy rendition stream
25.01.2021 16:41:20.479 *INFO* [JobHandler: /var/workflow/instances/server0/2021-01-25/asset_processing_on_sdk_8:/content/dam/core-components-examples/library/sample-assets/snowy-mountain-glacier.jpg/jcr:content/renditions/original] com.day.cq.dam.scene7.impl.process.AbstractScene7UploadProcess Skip S7 upload due to cannot find configuration for file: /content/dam/core-components-examples/library/sample-assets/snowy-mountain-glacier.jpg

```

**Comment by vladbailescu** [comment]
This happens because of https://github.com/adobe/aem-core-wcm-components/commit/e345cb5835b62fd834a272fc0e872be360a23993#diff-9508deac5c0f5c3bb2fe3e501606eb357ba21a375496380db3ad2ed34f71838bR60 and https://issues.apache.org/jira/browse/JCRVLT-495
