### ISSUE TITLE
NPE in AdaptiveImageServlet

### ISSUE THREAD

**Issue by joerghoh** [adobe/aem-core-wcm-components#1915]
## Bug Report

I find an NPE in the context of delivering a embedded image. It happens in the context of rendering the resourcetype ```project/components/image```.

```
15.12.2021 06:11:43.146 *ERROR* [87.243.134.48 [1639548703025] GET /content/.../_jcr_content/root/container/container/image.coreimg.85.800.jpeg/1638785609827/filename.jpeg HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.NullPointerException: image
        at com.day.image.Layer.<init>(Layer.java:917) [day-commons-gfx:2.1.52]
        at com.adobe.cq.wcm.core.components.internal.servlets.AdaptiveImageServlet.getLayer(AdaptiveImageServlet.java:492) [com.adobe.cq.core.wcm.components.core:2.17.12]
        at com.adobe.cq.wcm.core.components.internal.servlets.AdaptiveImageServlet.transformAndStreamAsset(AdaptiveImageServlet.java:372) [com.adobe.cq.core.wcm.components.core:2.17.12]
        at com.adobe.cq.wcm.core.components.internal.servlets.AdaptiveImageServlet.doGet(AdaptiveImageServlet.java:250) [com.adobe.cq.core.wcm.components.core:2.17.12]
```

The NPE is actually thrown by the Layer constructor when a NULL Image is provided.

**Current Behavior**
An internal server error is thrown

**Expected behavior/code**
A regular image being delivered; if it's a configuration error on the image component itself, the error message should contain more relevant information what's wrong.

**Environment**
AEM CS

**Comment by ky940819** [comment]
Just for further information - This error occurs because [AssetHandler.getImage(Rendition rendition)
](https://www.adobe.io/experience-manager/reference-materials/6-5/javadoc/com/day/cq/dam/api/handler/AssetHandler.html#getImage-com.day.cq.dam.api.Rendition-) may return null, but the `Layer` constructor parameter must not be null. 

See `AdaptiveImageServlet`:
```JAVA
    @NotNull
    private Layer getLayer(@NotNull EnhancedRendition rendition) throws IOException {
        AssetHandler assetHandler = assetStore.getAssetHandler(rendition.getMimeType());
        return new Layer(assetHandler.getImage(rendition.getRendition()));
    }
```

Since the `AssetHandler` does not provide explicit details on exactly why it is returning null, the only thing that we can say for sure is that we could not get the `BufferedImage` for the asset. 

Adjusting the `getLayer` method (shown above) to account for the fact that it might not actually be able to get the layer would require changing the annotation to `@Nullable` or the return type to `Optional<Layer>` - both cases would have ripple effects that would require significant reworking of the servlet. 

A more short term approach might be to check for the null and then throw an `IOException`, which would at least be caught in the `AdaptiveImageServlet#doGet()` method - resulting in a log message, metrics update, and sending a 404 to the client.

**Comment by joerghoh** [comment]
fixed by #1927 ?
