### ISSUE TITLE
NPE on PageDataImpl

### ISSUE THREAD

**Issue by AndreiAlexandruParaschiv** [adobe/aem-core-wcm-components#2330]
There are NPE errors 
` [35.182.104.198 [1665155874648] GET /favicon.ico HTTP/1.1] com.adobe.cq.wcm.core.components.internal.models.v1.datalayer.ComponentDataImpl Unable to generate dataLayer JSON string
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.adobe.cq.wcm.core.components.internal.models.v1.datalayer.PageDataImpl["xdm:template"]) `
`Caused by: java.lang.NullPointerException: null
	at com.adobe.cq.wcm.core.components.internal.models.v1.PageImpl.lambda$getComponentData$2(PageImpl.java:341) [com.adobe.cq.core.wcm.components.core:2.20.8]
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.adobe.cq.wcm.core.components.internal.models.v1.datalayer.PageDataImpl.getTemplatePath(PageDataImpl.java:66) [com.adobe.cq.core.wcm.components.core:2.20.8]
	at jdk.internal.reflect.GeneratedMethodAccessor215.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689) `

https://github.com/adobe/aem-core-wcm-components/blob/main/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/datalayer/PageDataImpl.java#L66
It needs to handle when the template path is null and throw IllegalArgumentException

**Comment by ky940819** [comment]
Just a quick look makes me think it comes from here:
https://github.com/adobe/aem-core-wcm-components/blob/cff5878e8e03edb55409d40a3dd85288cc559216/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/PageImpl.java#L340

An NPE would result if `getTemplate()` returns null.

Alternate option would be:
```JAVA
.withTemplatePath(() -> Optional.ofNullable(this.currentPage.getTemplate()).map(Template::getPath).orElse(null));
```
