### ISSUE TITLE
PDF Viewer | iPad Pro 11 shows "File Preview Error" 

### ISSUE THREAD

**Issue by pollenshukla** [adobe/aem-core-wcm-components#2331]
## Bug Report

**Current Behavior**
On the iPad 11 Pro, observed that https://documentcloud.adobe.com/dcpreviewdropin/2.21.2_1.1308.0/bootstrap.js:formatted breaks.

Console error:
```
bootstrap.js:formatted:31112 Uncaught (in promise) Error: getMetadata request failed
    at bootstrap.js:formatted:31112:23
    at bootstrap.js:formatted:51151:17
    at s (dc-mobx.js:16:23365)
    at Yt (dc-mobx.js:16:45501)
    at e.track (dc-mobx.js:16:48113)
    at e.onInvalidate (dc-mobx.js:16:23340)
    at e.runReaction (dc-mobx.js:16:47892)
    at pn (dc-mobx.js:16:50058)
    at ln (dc-mobx.js:16:49694)
    at dc-mobx.js:16:54954
```

**Expected behavior/code**
PDF viewer should load the PDF on iPad 11 Pro as well.

**Environment**
- AEM version 6.5.10
- Core Components version - 2.10.0+

**Possible Solution**
Make the bootstrap library compatible the way it works for other iPhone/iPad devices.

**Additional context / Screenshots**
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/28946768/194653414-cec3a58c-1b84-4c88-a291-581e658a6d64.png">

**Comment by pollenshukla** [comment]
Works on version 2.20.6
