### ISSUE TITLE
Review: Build does not work with Java 17

### ISSUE THREAD

**Issue by joerghoh** [adobe/aem-core-wcm-components#2357]
## Bug Report

**Current Behavior**
When running a build with Java 17, the tests fails with exceptions like this:

```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:184)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:166)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:152)
	at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:82)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3390)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1930)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:207)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:116)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3397)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:254)

```

**Expected behavior/code**
well, it should build :-)

**Environment**
- Main branch
- JDK 17

**Possible Solution**

Mockito needs to get updated to at least version 4.4.0 (right now the version is a very old 2.24.5 :-(

**Comment by ky940819** [comment]
Hello, 

I put together a branch to allow for JDK 17 compatibility. 
Upgrading mockito was only one step in a long dependency cascade (not unexpected in maven!). 
Since I was half-forced to update many of the dependencies, i took that opportunity to just update all of the dependencies so that they are:

1. *Non-Test* dependencies were updated to the latest usable in 6.5.13.0 (current minimum supported version for core components)
2. *Test* dependencies were updated to either:
    - latest if they were a pure test utility; or
    -  matching AEM 6.5.13.0 if they were an implementation of something available in AEM.

The other primary issues I ran into were updating `aem-mocks` to the latest version required some changes to the test code, and getting it to build in java 17 required some changes in how reflection is used in tests.

If you or someone else would like to review these changes, I'd be happy to post them.

Kyle

**Comment by joerghoh** [comment]
Hi @ky940819 

Yes, it would be great if you post a (preliminary) PR for review. Thanks!

**Comment by bpauli** [comment]
@adobe export issue to Jira project SITES as Bug

**Comment by bpauli** [comment]
@ky940819 Thank you for all the work in this PR!
