### ISSUE TITLE
[Image] getSeoFriendlyName not respecting AssetDelivery seoname pattern

### ISSUE THREAD

**Issue by aderler** [adobe/aem-core-wcm-components#2385]
## Bug Report

**Current Behavior**
Image assets containing non-word characters in the filename trigger errors when asset delivery through dynamic media is enabled for the image component (`enableAssetDelivery=true`).

As described in https://experienceleague.adobe.com/docs/experience-manager-core-components/using/developing/web-optimized-image-delivery.html?lang=en#can-i-use-web-optimized-image-delivery-with-my-own-component%3F the seoname must be of pattern `[\w-]+`:

> seoname – User-defined, SEO-centric name to be appended to the image URL, may contain hyphens, must be of pattern ([\w-]+) (e.g.: my-friend-the-unicorn)

However, the method `com.adobe.cq.wcm.core.components.internal.models.v1.ImageImpl#getSeoFriendlyName` does not follow that pattern. Instead, it only replaces underscores with dash and performs URL encoding.

As a result, if an image with a filename containing not allowed characters (e.g. `test(invalid).jpg`) is uploaded, it will cause an error that is written to the log output each time the AssetDelivery is invoked (`com.day.cq.wcm.core.impl.woid.AssetDeliveryImpl::getDeliveryURL`).

Stacktrace:
```
24.11.2022 11:41:49.562 [cm-p15646-e36687-aem-author-574cb7c578-4z568] *ERROR* [85.237.29.164 [1669290108437] GET /content/mysite/dynamic-media-test.html HTTP/1.1] com.day.cq.wcm.core.impl.woid.AssetDeliveryImpl Error while fetching url from dm service 
java.lang.IllegalArgumentException: Invalid seoname!
	at com.adobe.cq.dam.dm.weboptimized.delivery.impl.ImageDeliveryURLBuilderImpl.buildURL(ImageDeliveryURLBuilderImpl.java:220) [com.adobe.cq.dam.dm-weboptimized-delivery-impl:0.42.0]
	at com.day.cq.wcm.core.impl.woid.AssetDeliveryImpl.getDeliveryURL(AssetDeliveryImpl.java:188) [com.day.cq.wcm.cq-wcm-core:5.14.56]
	at com.adobe.cq.wcm.core.components.internal.helper.image.AssetDeliveryHelper.getSrc(AssetDeliveryHelper.java:123) [com.adobe.cq.core.wcm.components.core:2.20.8]
	at com.adobe.cq.wcm.core.components.internal.models.v1.ImageImpl.initModel(ImageImpl.java:274) [com.adobe.cq.core.wcm.components.core:2.20.8]
	at com.adobe.cq.wcm.core.components.internal.models.v2.ImageImpl.initModel(ImageImpl.java:153) [com.adobe.cq.core.wcm.components.core:2.20.8]
	at com.adobe.cq.wcm.core.components.internal.models.v3.ImageImpl.initModel(ImageImpl.java:70) [com.adobe.cq.core.wcm.components.core:2.20.8]
```

Steps to reproduce:

1. Enable Asset Delivery for the image component
2. Upload image asset with non-word characters in filename (e.g. `test(invalid).jpg`)
3. Add an image component with a reference to the previously uploaded asset to a page
4. Verify the log output when rendering the page

This affects all existing image component versions (ImageV1, ImageV2, ImageV3).

**Expected behavior/code**
Filenames of images should be properly converted to SEO friendly names in the image component. The AssetDelivery should not log any errors, even when the original filename contains characters that are not allowed for the seoname.

**Environment**
- AEM version: AEMaaCS 2022.10.9398.20221020T071514Z
- Core Components version: 2.21.2

**Possible Solution**
Adapt `com.adobe.cq.wcm.core.components.internal.models.v1.ImageImpl#getSeoFriendlyName`  to filter or replace characters that do not follow the seoname pattern.

**Comment by bpauli** [comment]
@aderler Thank you for spotting this and for providing a PR!
