### ISSUE TITLE
[ContentFragment] Exception while rendering content fragment variation

### ISSUE THREAD

**Issue by craghav** [adobe/aem-core-wcm-components#531]
Content Fragment Variation is not displayed in publish instance.

Steps to replicate:

1) Create a Content Fragment Model using content fragment editor.
2) Create a Content Fragment in using using the newly create Content Fragment Model with master and one more variation (variant1)
3) Create an AEM page and add content fragment (v1) component
4) Select the newly created content Fragment and choose the variant as variant1.
5) Publish the page and access the page in publish.
6) Issue - No values of the Content Fragment will be displayed.
7) Log in to publish and access the page, the values will be displayed.

`04.04.2019 16:24:58.281 *ERROR* [0:0:0:0:0:0:0:1 [1554387898044] GET /content/we-retail/language-masters/en/experience/arctic-surfing-in-lofoten.html HTTP/1.1] org.apache.sling.scripting.sightly.compiler.util.ObjectModel Cannot access method dataType on object com.adobe.cq.wcm.core.components.extension.contentfragment.internal.models.v1.ContentFragmentImpl$ElementImpl@506c8340
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor176.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.sling.scripting.sightly.compiler.util.ObjectModel.invokeBeanMethod(ObjectModel.java:394) [org.apache.sling.scripting.sightly.compiler:1.0.20.1_3_1]
	at org.apache.sling.scripting.sightly.compiler.util.ObjectModel.resolveProperty(ObjectModel.java:123) [org.apache.sling.scripting.sightly.compiler:1.0.20.1_3_1]
	at org.apache.sling.scripting.sightly.render.AbstractRuntimeObjectModel.getProperty(AbstractRuntimeObjectModel.java:148) [org.apache.sling.scripting.sightly.compiler.java:1.0.22.1_3_1]
....................
Caused by: java.lang.NullPointerException: null
	at com.adobe.cq.wcm.core.components.extension.contentfragment.internal.models.v1.ContentFragmentImpl$ElementImpl.getContentType(ContentFragmentImpl.java:433)
	at com.adobe.cq.wcm.core.components.extension.contentfragment.internal.models.v1.ContentFragmentImpl$ElementImpl.isMultiLine(ContentFragmentImpl.java:438)`

**Comment by richardhand** [comment]
Hi @craghav, I've been unable to replicate this behaviour. Could you let us know what environment you're testing with:

- AEM version and patch level (e.g. AEM 6.3 SP1 CFP2)
- Core Components version (e.g. 2.3.2)
- Core Components extension version (e.g. 1.0.12)
- JRE version (e.g. `Java(TM) SE Runtime Environment (build 1.8.0_152-b16)`)

Thanks!

**Comment by craghav** [comment]
@richardhand : The issue was replicated in
AEM : 6.4.1
Core Components version 2.3.0
Core Component extension version 1.0.10
Java version : 8

The issue can be reproduced in the latest version of the core components too. Please note the issue is replicable in publish instance only. 
The issue is not replicable in AEM 6.4.3 though.

**Comment by richardhand** [comment]
Thanks @craghav - I was able to replicate the problem on 6.4.1.0, but not 6.4.2.0, perhaps you can confirm? 

According to the [historical versions](https://github.com/adobe/aem-core-wcm-components/blob/master/VERSIONS.md), Core Components `2.3.0` and Core Components Extension `1.0.10` have `6.4.2.0` as their minimum requirement. The recommendation would therefore be to upgrade.
