### ISSUE TITLE
TeaserImplTest & AdaptiveImageServletTest unit tests are failing with JDK12

### ISSUE THREAD

**Issue by bpauli** [adobe/aem-core-wcm-components#731]
Due to the changes in the reflection field access with JDK12 the unit tests TeaserImplTest and AdaptiveImageServletTest are failing.

Example output:
```
[ERROR] testWithInvalidDesignWidth  Time elapsed: 0.215 s  <<< ERROR!
java.lang.NoSuchFieldException: modifiers
	at com.adobe.cq.wcm.core.components.internal.servlets.AdaptiveImageServletTest.setFinalStatic(AdaptiveImageServletTest.java:637)
	at com.adobe.cq.wcm.core.components.internal.servlets.AdaptiveImageServletTest.testWithInvalidDesignWidth(AdaptiveImageServletTest.java:184)
```

**Comment by acollign** [comment]
thanks for logging the issue @bpauli !
