### ISSUE TITLE
[Search] Null pointer exception in SearchResultServlet.getResults(SearchResultServlet.java:172)

### ISSUE THREAD

**Issue by josephh** [adobe/aem-core-wcm-components#929]
⚠️ We are using core components v2.3.0; prior to filing this issue I tried setting the core components all version to 2.8.0 but without success, so reverted to 2.3.0. (Upon deploying core components 2.8.0 to our test environment, pages were not rendered and an error was shown `Line 44, column 1936 : com.adobe.cq.wcm.core.components.models.Page cannot be resolved to a type`).

## Bug Report

**Current Behavior**
We have included the core Search component in our custom AEM components; we have 'proxied' via our codebase the Search component and added additional styling and a client-side script to append the Search <section> to our html <nav> element. We have then added the Search to our authorable templates and set the component's policy.   The search component works OK when requests are issued directly to the publisher.  When requests are sent via Apache dispatcher (or via the DNS proxy and then Apache Dispatcher) we see a Null Pointer Exception from the SearchResultServlet in the publisher logs.  See details added below.  Are there additional AEM configuration steps we have overlooked for this to work via the Dispatcher?

**Expected behavior/code**
The search component results are returned and displayed by the component in both pages requested directly from the publisher and via the dispatcher. 

**Environment**
- AEM 6.4 SP3
- Core Components version 2.3.0
- `java version "1.8.0_131"`
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Additional context / Screenshots**
#### publisher error.log showing null pointer exception
```java
21.02.2020 14:51:50.181 *ERROR* [141.101.99.69 [1582296710178] GET /content/denplan/denplan-homepage.searchresults.json/_jcr_content/root/quick_search.html HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught Throwable
java.lang.NullPointerException: null
        at com.adobe.cq.wcm.core.components.internal.servlets.SearchResultServlet.getResults(SearchResultServlet.java:172) [com.adobe.cq.core.wcm.components.core:2.3.0]
        at com.adobe.cq.wcm.core.components.internal.servlets.SearchResultServlet.doGet(SearchResultServlet.java:104) [com.adobe.cq.core.wcm.components.core:2.3.0]
        at org.apache.sling.api.servlets.SlingSafeMethodsServlet.mayService(SlingSafeMethodsServlet.java:266) [org.apache.sling.api:2.18.4]
        at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:342) [org.apache.sling.api:2.18.4]
        at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:374) [org.apache.sling.api:2.18.4]
        at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:552) [org.apache.sling.engine:2.6.16]
        at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44) [org.apache.sling.engine:2.6.16]
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:82) [org.apache.sling.engine:2.6.16]
        at com.day.cq.wcm.core.impl.WCMDebugFilter.doFilter(WCMDebugFilter.java:138) [com.day.cq.wcm.cq-wcm-core:5.11.250]
     ...
```
#### publisher request.log - following input into the search component (direct to request publisher) 😄 
> 21/Feb/2020:14:51:02 +0000 [181] -> GET /content/denplan/denplan-homepage.searchresults.json/_jcr_content/root/quick_search?fulltext=teeth&resultsOffset=0 HTTP/1.1 
21/Feb/2020:14:51:02 +0000 [181] <- 200 application/json 15ms
#### publisher request.log - following input into the search component (request via dispatcher) 😒 
> 21/Feb/2020:14:51:50 +0000 [185] -> GET /content/denplan/denplan-homepage.searchresults.json/_jcr_content/root/quick_search.html?fulltext=teeth&resultsOffset=0 HTTP/1.1
21/Feb/2020:14:51:50 +0000 [185] <- 500 text/html 8ms
#### Dispatcher output - request via DNS proxy and dispatcher (dispatcher filter allows the request)
```[Fri Feb 21 14:48:53 2020] [D] [pid 55354] Found farm denplan for denplan
[Fri Feb 21 14:48:53 2020] [D] [pid 55354] checking [/content/denplan/denplan-homepage.searchresults.json/_jcr_content/root/quick_search.html]
[Fri Feb 21 14:48:53 2020] [D] [pid 55354] request contains a query string: fulltext=teeth&resultsOffset=0
[Fri Feb 21 14:48:53 2020] [D] [pid 55354] cache-action for [/content/denplan/denplan-homepage.searchresults.json/_jcr_content/root/quick_search.html]: NONE
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] Filter rule entry /0007 allowed 'GET /content/denplan/denplan-homepage.searchresults.json/_jcr_content/root/quick_search.html?fulltext=teeth&resultsOffset=0 HTTP/1.0'
[Fri Feb 21 14:48:53 2020] [D] [pid 55354] Dropping socket after 106 seconds of inactivity: 172.16.185.6:4503
[Fri Feb 21 14:48:53 2020] [D] [pid 55354] Creating new socket: 172.16.185.6:4503
[Fri Feb 21 14:48:53 2020] [D] [pid 55354] Connected to backend rend01 (172.16.185.6:4503)
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.uri = "/content/denplan/denplan-homepage.searchresults.json/_jcr_content/root/quick_search.html"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[X-Forwarded-Host] = "test.denplan.co.uk"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[X-Real-IP] = "162.158.155.96"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[Host] = "denplan"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[Accept-Encoding] = "gzip"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[CF-IPCountry] = "GB"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[CF-RAY] = "568986158bcd3588-LHR"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[X-Forwarded-Proto] = "https"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[CF-Visitor] = "{"scheme":"https"}"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[user-agent] = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[accept] = "*/*"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[sec-fetch-site] = "same-origin"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[sec-fetch-mode] = "cors"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[referer] = "https://test.denplan.co.uk/"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[accept-language] = "en-GB,en-US;q=0.9,en;q=0.8"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[cookie] = "_fbp=fb.2.1575223621909.796302835; _ga=GA1.3.835683446.1576498767; _gcl_au=1.1.1946738999.1576498767; __cfduid=d9adebd149f3417ce209a11527dc996081580920479; cc_cookie_accept=true; check=true; AMCVS_C29B148954F6424A0A4C98BC%40AdobeOrg=1; AMCV_C29B148954F6424A0A4C98BC%40AdobeOrg=1406116232%7CMCMID%7C63526834135806747622898513709455625955%7CMCAAMLH-1582901144%7C9%7CMCAAMB-1582901144%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1582303544s%7CNONE%7CvVersion%7C2.5.0; mbox=PC#a8d7dc3080c6409fbe80ca755b6d108f.28_0#1644586734|session#d371628bb3e94b139d3101a4a7d043ba#1582298205"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[CF-Connecting-IP] = "81.128.191.42"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[CDN-Loop] = "cloudflare"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[Via] = "1.0 denplan (dispatcher)"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[X-Forwarded-For] = "162.158.155.96, 172.16.184.6"
[Fri Feb 21 14:48:53 2020] [T] [pid 55354] request.headers[Server-Agent] = "Communique-Dispatcher"
[Fri Feb 21 14:48:53 2020] [D] [pid 55354] response.status = 500

**Comment by vladbailescu** [comment]
It seems your dispatcher is injecting an extra `.html` at

> publisher request.log - following input into the search component (request via dispatcher) 😒
> 21/Feb/2020:14:51:50 +0000 [185] -> GET /content/denplan/denplan-homepage.searchresults.json/_jcr_content/root/quick_search **.html** ?fulltext=teeth&resultsOffset=0 HTTP/1.1
> 21/Feb/2020:14:51:50 +0000 [185] <- 500 text/html 8ms

**Comment by josephh** [comment]
Ah! thanks for pointing that out @vladbailescu I completely missed it.  I am sure that is the root of the problem.

**Comment by josephh** [comment]
Yes, apache mod_rewrite is the culprit 😒
